app = "external-mcp-server"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/health"

[env]
  # Environment variables for API access
  # SHORTCUT_API_TOKEN = "your-token-here"
  # DD_API_KEY = "your-datadog-api-key"
  # DD_APP_KEY = "your-datadog-app-key"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512